# auction_items.py

items_list = [
    # --- Antiques & History ---
    "Ancient Roman Coin (c. 100 AD)",
    "Victorian Era Silver Pocket Watch",
    "Piece of the Berlin Wall",
    "18th Century Pirate Telescope",
    "Civil War Era Cannonball",
    "Vintage Typewriter (1920s Remington)",
    "Fossilized Megalodon Tooth",
    "Medieval Iron Key",
    "19th Century Ship's Compass",
    "Original WW2 Ration Book",
    "Antique Samurai Sword (Katana)",
    "Vintage Rotary Phone (Red)",
    "Ancient Egyptian Scarab Beetle Amulet",
    "1900s Stereoscope Viewer",
    "Piece of Coal from the Titanic",

    # --- Pop Culture & Movies ---
    "Lightsaber Replica Signed by Mark Hamill",
    "Hoverboard Prop from Back to the Future II",
    "Iron Man Helmet (Wearable Replica)",
    "Original Script from 'Friends' (Signed)",
    "Harry Potter's Wand (Film Prop Replica)",
    "Jurassic Park Amber Cane Replica",
    "Batman's Batarang (Dark Knight Replica)",
    "Pokemon Pikachu Illustrator Card",
    "Marvel Infinity Gauntlet Replica",
    "Signed Poster of 'The Godfather'",
    "Stormtrooper Helmet (Life Size)",
    "Lord of the Rings 'One Ring' Replica (Gold Plated)",
    "Ghostbusters Proton Pack Replica",
    "Funko Pop! Rare Metallic Chase Edition",
    "Original Animation Cel from 'The Simpsons'",

    # --- Sports Memorabilia ---
    "Basketball Signed by Michael Jordan",
    "Soccer Ball Signed by Lionel Messi",
    "Boxing Glove Signed by Muhammad Ali",
    "1927 New York Yankees Cap (Replica)",
    "Super Bowl MVP Jersey",
    "Tennis Racket Used by Serena Williams",
    "F1 Driver's Helmet (Replica)",
    "Baseball Bat Signed by Babe Ruth",
    "Signed Cristiano Ronaldo Jersey",
    "Hockey Puck from 1980 'Miracle on Ice'",
    "Ticket Stub from 1966 World Cup Final",
    "Golf Flag Signed by Tiger Woods",
    "Usain Bolt Signed Running Shoes",
    "Signed WWE Championship Belt",
    "1952 Topps Mickey Mantle Card (Reprint)",

    # --- Luxury Watches & Jewelry ---
    "Rolex Submariner (Vintage)",
    "Omega Speedmaster 'Moonwatch'",
    "Cartier Tank Watch",
    "Tiffany & Co. Silver Necklace",
    "Diamond Tennis Bracelet (2 Carat)",
    "Patek Philippe Nautilus (Replica)",
    "Vintage Pearl Earrings",
    "Gold Sovereign Coin Ring",
    "Sapphire and Diamond Brooch",
    "Tag Heuer Formula 1 Watch",
    "Bulgari Serpenti Bracelet",
    "Breitling Navitimer",
    "Emerald Cut Ruby Ring",
    "Vintage Chanel Brooch",
    "Platinum Wedding Band",

    # --- Technology & Gaming ---
    "Original 1984 Apple Macintosh Computer",
    "Nintendo Game Boy (Sealed Box)",
    "PlayStation 5 (Gold Plated Edition)",
    "Retro Arcade Cabinet (Pac-Man)",
    "First Generation iPhone (Sealed)",
    "VR Headset (Latest Model)",
    "High-End Gaming PC Setup",
    "Drone with 4K Camera",
    "Vintage Nintendo NES Console",
    "SpaceX Starlink Dish Kit",
    "Tesla Flamethrower",
    "3D Printer (Industrial Grade)",
    "Smart Mirror with Touchscreen",
    "Robot Dog (Boston Dynamics Spot)",
    "Crypto Cold Storage Wallet (Loaded with 0.1 BTC)",

    # --- Travel & Experiences ---
    "7-Night Stay in a Water Villa (Maldives)",
    "Private Helicopter Tour of NYC",
    "Safari Trip for Two in Kenya",
    "VIP Tickets to Coachella Music Festival",
    "Zero Gravity Experience Flight",
    "Dinner in the Eiffel Tower",
    "Northern Lights Tour (Iceland)",
    "Disney World All-Access VIP Pass",
    "F1 Grand Prix Paddock Club Tickets",
    "Submarine Dive to the Great Barrier Reef",
    "Castle Stay in Scotland (Weekend)",
    "Hot Air Balloon Ride over Cappadocia",
    "Wine Tasting Tour in Tuscany",
    "Space Camp Experience for Adults",
    "Super Bowl 50 Yard Line Tickets",

    # --- Art & Decor ---
    "Oil Painting: 'Starry Night' (High Quality Replica)",
    "Banksy 'Girl with Balloon' Print",
    "Modern Abstract Metal Sculpture",
    "Hand-Woven Persian Rug",
    "Life-Size Statue of David (Replica)",
    "Japanese Cherry Blossom Watercolor",
    "Vintage Neon Bar Sign",
    "Crystal Chandelier (Swarovski)",
    "Hand-Blown Glass Vase from Murano",
    "Street Art Canvas by Local Artist",
    "Limited Edition KAWS Figure",
    "Salvador Dali Melted Clock Sculpture",
    "Framed Map of the World (17th Century Style)",
    "Bronze Horse Statue",
    "Digital NFT Art Frame",

    # --- Rare Books & Comics ---
    "First Edition 'The Great Gatsby'",
    "Action Comics #1 (Superman Debut - Reprint)",
    "Signed Copy of 'Harry Potter and the Sorcerer's Stone'",
    "The Hobbit (1937 First Edition Replica)",
    "Complete Encyclopedia Britannica Set (1911)",
    "Detective Comics #27 (Batman Debut - Reprint)",
    "Leather Bound Shakespeare Collection",
    "Signed Stephen King Novel",
    "Amazing Fantasy #15 (Spider-Man Debut - Reprint)",
    "Original 1950s Sci-Fi Pulp Magazine",
    "Gutenberg Bible Page (Facsimile)",
    "Da Vinci Code (Signed by Dan Brown)",
    "Vintage Vogue Magazine (1950s)",
    "Sherlock Holmes Collection (Vintage)",
    "Marvel Secret Wars #8 (Black Suit Spidey)",

    # --- Musical Instruments ---
    "Fender Stratocaster Guitar (1960s Reissue)",
    "Violin from 1800s Germany",
    "Steinway Baby Grand Piano",
    "Gibson Les Paul Goldtop",
    "Drum Sticks Signed by Dave Grohl",
    "Vintage Saxophone (Selmer Mark VI)",
    "Harmonica Used by Bob Dylan",
    "Synthesizer (Moog Grandmother)",
    "Ukulele Signed by Israel Kamakawiwo'ole",
    "Electric Bass Guitar (Fender Jazz)",
    "Vintage Accordion",
    "Clarinet (Buffet Crampon)",
    "Microphone Used by Elvis (Replica)",
    "Signed Sheet Music by Beethoven (Facsimile)",
    "Cello (Professional Grade)",

    # --- Vehicles & Models ---
    "1967 Ford Mustang Shelby GT500 (Diecast Model)",
    "Vespa Scooter (Vintage 1970s)",
    "Harley Davidson Leather Jacket",
    "Porsche 911 Engine Block Coffee Table",
    "Model Ship: HMS Victory",
    "Electric Skateboard (Boosted Board)",
    "Vintage Bicycle (Penny Farthing)",
    "Ferrari Key (Collectible)",
    "Lego Millennium Falcon (Ultimate Collector Series)",
    "Remote Control Jet Plane (Gas Powered)",
    "Go-Kart (Professional Racing)",
    "Segway Personal Transporter",
    "Classic Mini Cooper (Toy Car 1960s)",
    "BMW M3 Steering Wheel",
    "Yacht Charter for a Day"

    # --- Anime & Manga ---
    "Dragon Ball Z: Set of 7 Crystal Dragon Balls",
    "Naruto: Hidden Leaf Village Headband (Replica)",
    "One Piece: Luffy's Straw Hat (Authentic Replica)",
    "Death Note: The Notebook (Replica with Rules)",
    "Attack on Titan: Survey Corps Green Cloak",
    "Sailor Moon: Moon Stick (Proplica Edition)",
    "Fullmetal Alchemist: Edward Elric's Pocket Watch",
    "Pokémon: Master Ball (Diecast Replica)",
    "Demon Slayer: Tanjiro's Nichirin Sword (Replica)",
    "Studio Ghibli: Totoro Plush (Giant Size)",
    "Evangelion: Unit-01 Model Kit (Perfect Grade)",
    "Cowboy Bebop: Spike Spiegel's Jericho 941 (Prop)",
    "JoJo's Bizarre Adventure: Stone Mask Replica",
    "Akira: Kaneda's Red Jacket",
    "Bleach: Ichigo's Hollow Mask",

    # --- Video Games (Classics & Modern) ---
    
    # Action & Adventure
    "The Legend of Zelda: Breath of the Wild",
    "God of War (2018)",
    "Grand Theft Auto V",
    "Red Dead Redemption 2",
    "Uncharted 4: A Thief's End",
    "The Last of Us Part II",
    "Horizon Zero Dawn",
    "Assassin's Creed II",
    "Spider-Man (PS4)",
    "Ghost of Tsushima",
    "Batman: Arkham City",
    "Metal Gear Solid V: The Phantom Pain",
    "Shadow of the Colossus",
    "Control",
    "Sekiro: Shadows Die Twice",

    # RPG (Role-Playing Games)
    "The Witcher 3: Wild Hunt",
    "Elden Ring",
    "Skyrim: The Elder Scrolls V",
    "Final Fantasy VII Remake",
    "Mass Effect 2",
    "Persona 5 Royal",
    "Fallout: New Vegas",
    "Dark Souls III",
    "Bloodborne",
    "Cyberpunk 2077",
    "Chrono Trigger",
    "Pokémon Red/Blue (Original Cartridge)",
    "Diablo II: Resurrected",
    "Baldur's Gate 3",
    "Kingdom Hearts II",

    # FPS (First-Person Shooters)
    "Halo: Combat Evolved",
    "Call of Duty 4: Modern Warfare",
    "Doom Eternal",
    "Half-Life 2",
    "BioShock",
    "Overwatch 2",
    "Counter-Strike: Global Offensive",
    "Destiny 2",
    "GoldenEye 007 (N64)",
    "Titanfall 2",
    "Rainbow Six Siege",
    "Team Fortress 2",
    "Wolfenstein II: The New Colossus",
    "Left 4 Dead 2",
    "Apex Legends",

    # Platformers
    "Super Mario Odyssey",
    "Super Mario 64",
    "Celeste",
    "Hollow Knight",
    "Sonic the Hedgehog 2",
    "Donkey Kong Country",
    "Crash Bandicoot N. Sane Trilogy",
    "Spyro Reignited Trilogy",
    "Ori and the Will of the Wisps",
    "Cuphead",
    "LittleBigPlanet",
    "Ratchet & Clank: Rift Apart",
    "Shovel Knight",
    "Banjo-Kazooie",
    "Metroid Dread",

    # Strategy & MOBA
    "League of Legends",
    "Dota 2",
    "Civilization VI",
    "StarCraft II",
    "XCOM 2",
    "Age of Empires II: Definitive Edition",
    "Total War: Warhammer III",
    "Fire Emblem: Three Houses",
    "Crusader Kings III",
    "Command & Conquer: Red Alert 2",

    # Horror & Survival
    "Resident Evil 4 (Remake)",
    "Silent Hill 2",
    "Minecraft",
    "Terraria",
    "Subnautica",
    "Dead Space (Remake)",
    "Alien: Isolation",
    "Amnesia: The Dark Descent",
    "Valheim",
    "The Forest",

    # Fighting
    "Street Fighter 6",
    "Super Smash Bros. Ultimate",
    "Tekken 7",
    "Mortal Kombat 11",
    "Dragon Ball FighterZ",
    "Soulcalibur VI",
    "Marvel vs. Capcom 2",
    "Guilty Gear Strive",
    "Injustice 2",
    "King of Fighters XV",

    # Indie Hits & Simulation
    "Stardew Valley",
    "Undertale",
    "Animal Crossing: New Horizons",
    "The Sims 4",
    "Among Us",
    "Hades",
    "Disco Elysium",
    "Rocket League",
    "Portal 2",
    "Tetris Effect",
]