# auction_items.py

items_list = [
    # --- Antiques & History ---
    "Ancient Roman Coin (c. 100 AD)",
    "Victorian Era Silver Pocket Watch",
    "Piece of the Berlin Wall",
    "18th Century Pirate Telescope",
    "Civil War Era Cannonball",
    "Vintage Typewriter (1920s Remington)",
    "Fossilized Megalodon Tooth",
    "Medieval Iron Key",
    "19th Century Ship's Compass",
    "Original WW2 Ration Book",
    "Antique Samurai Sword (Katana)",
    "Vintage Rotary Phone (Red)",
    "Ancient Egyptian Scarab Beetle Amulet",
    "1900s Stereoscope Viewer",
    "Piece of Coal from the Titanic",
    "Ancient Greek Pottery Amphora (c. 400 BC)",
    "Ming Dynasty Porcelain Vase",
    "Viking Battle Axe (Rusted)",
    "Aztec Gold Coin (Replica)",
    "Mayan Temple Stone Fragment",
    "Civil War Musket Rifle (Deactivated)",
    "WWI Doughboy Helmet",
    "Cold War Spy Camera (Minox)",
    "Fragment of a Moon Rock",
    "Triceratops Brow Horn Fossil",
    "Woolly Mammoth Tusk Section",
    "Siberian Meteorite Chunk",
    "Ancient Chinese Bamboo Scroll",
    "Babylonian Clay Tablet (Cuneiform)",
    "Samurai Yoroi Armor Suit",
    "Medieval Knight's Gauntlets",
    "Flintlock Duelist Pistol (18th Century)",
    "Spanish Armada Ship Anchor",
    "Brass Sextant (Nautical)",
    "Astronomical Astrolabe",
    "Gothic Cathedral Gargoyle Head",
    "Medieval Wax Seal Stamp",
    "Royal Signet Ring (Gold)",
    "Replica Crown Jewels of England",
    "Royal Scepter (Velvet & Gold)",
    "French Tapestry (17th Century)",
    "Murano Glass Chandelier (Antique)",
    "Russian Orthodox Icon Painting",
    "Silver Reliquary Box",
    "Antique Ivory Chess Set",
    "Terracotta Warrior Statue (Replica)",
    "Egyptian Sphinx Miniature (Limestone)",
    "Native American Totem Pole (Cedar)",
    "Traditional Dreamcatcher (Authentic)",
    "Ceremonial Peace Pipe",
    "Obsidian Arrowhead Collection",
    "Gold Nugget from California Gold Rush",
    "Old West Miner's Pickaxe",
    "Railroad Lantern (19th Century)",
    "Victorian Oil Lamp",
    "Brass Candle Holder Set",
    "Antique Spinning Wheel",
    "Blacksmith's Anvil (100lbs)",
    "Vintage Farrier Tools",
    "Wild West Sheriff Badge",
    "Wanted Poster (Billy the Kid)",
    "Telegraph Machine (Morse Code)",
    "Antique Cash Register (Brass)",
    "Barber Shop Pole (Vintage Motorized)",
    "Cast Iron Stove (1900s)",
    "Singer Sewing Machine (Treadle)",
    "Gramophone with Brass Horn",
    "Vinyl Record Player (1950s Cabinet)",

    # --- Pop Culture & Movies ---
    "Lightsaber Replica Signed by Mark Hamill",
    "Hoverboard Prop from Back to the Future II",
    "Iron Man Helmet (Wearable Replica)",
    "Original Script from 'Friends' (Signed)",
    "Harry Potter's Wand (Film Prop Replica)",
    "Jurassic Park Amber Cane Replica",
    "Batman's Batarang (Dark Knight Replica)",
    "Pokemon Pikachu Illustrator Card",
    "Marvel Infinity Gauntlet Replica",
    "Signed Poster of 'The Godfather'",
    "Stormtrooper Helmet (Life Size)",
    "Lord of the Rings 'One Ring' Replica (Gold Plated)",
    "Ghostbusters Proton Pack Replica",
    "Funko Pop! Rare Metallic Chase Edition",
    "Original Animation Cel from 'The Simpsons'",
    "Star Trek: Phaser Type-2 Prop",
    "Doctor Who: Sonic Screwdriver (10th Doctor)",
    "Doctor Who: TARDIS Model (Light & Sound)",
    "Predator: Bio-Mask Replica",
    "Alien: Xenomorph Egg Prop",
    "Terminator: T-800 Endoskeleton Arm",
    "RoboCop: Auto-9 Prop Gun",
    "Gremlins: Gizmo Puppet",
    "E.T. the Extra-Terrestrial Stunt Doll",
    "Child's Play: Chucky Doll (Good Guys Box)",
    "Nightmare on Elm Street: Freddy's Glove",
    "Friday the 13th: Jason Vorhees Hockey Mask",
    "Halloween: Michael Myers Mask",
    "Scream: Ghostface Mask & Robe",
    "Saw: Billy the Puppet Tricycle",
    "The Conjuring: Annabelle Doll Replica",
    "The Shining: 'Here's Johnny' Axe Prop",
    "Indiana Jones: Fedora & Whip Set",
    "Indiana Jones: Holy Grail Cup",
    "The Goonies: Treasure Map Prop",
    "Back to the Future: Sports Almanac",
    "Ghostbusters: Ghost Trap Prop",
    "Ghostbusters: P.K.E. Meter",
    "Beetlejuice: Handbook for the Recently Deceased",
    "The Matrix: Red & Blue Pill Prop Case",
    "The Matrix: Neo's Sunglasses",
    "V for Vendetta: Guy Fawkes Mask",
    "300: Spartan Helmet & Shield",
    "Gladiator: Maximus Helmet Replica",
    "Braveheart: William Wallace Claymore",
    "Zorro: Mask, Hat & Rapier Set",
    "James Bond: Golden Gun Replica",
    "James Bond: Aston Martin DB5 Model",
    "Mission Impossible: Latex Mask Maker Prop",
    "Top Gun: Maverick's Flight Helmet",
    "Rocky: Boxing Shorts (American Flag)",
    "Rambo: Survival Knife (First Blood)",
    "Karate Kid: Miyagi-Do Headband",
    "Cobra Kai: Dojo Gi",
    "Hunger Games: Mockingjay Pin",
    "Harry Potter: Golden Snitch (Metal)",
    "Harry Potter: Marauder's Map",
    "Harry Potter: Time Turner Necklace",
    "Lord of the Rings: Sting Sword (Frodo)",
    "Lord of the Rings: Gandalf's Staff",
    "Hobbit: Key to Erebor",
    "Game of Thrones: Iron Throne Miniature",
    "Game of Thrones: Dragon Egg Set",
    "Game of Thrones: Hand of the King Pin",
    "Stranger Things: Demogorgon Figure",

    # --- Sports Memorabilia ---
    "Basketball Signed by Michael Jordan",
    "Soccer Ball Signed by Lionel Messi",
    "Boxing Glove Signed by Muhammad Ali",
    "1927 New York Yankees Cap (Replica)",
    "Super Bowl MVP Jersey",
    "Tennis Racket Used by Serena Williams",
    "F1 Driver's Helmet (Replica)",
    "Baseball Bat Signed by Babe Ruth",
    "Signed Cristiano Ronaldo Jersey",
    "Hockey Puck from 1980 'Miracle on Ice'",
    "Ticket Stub from 1966 World Cup Final",
    "Golf Flag Signed by Tiger Woods",
    "Usain Bolt Signed Running Shoes",
    "Signed WWE Championship Belt",
    "1952 Topps Mickey Mantle Card (Reprint)",

    # --- Luxury Watches & Jewelry ---
    "Rolex Submariner (Vintage)",
    "Omega Speedmaster 'Moonwatch'",
    "Cartier Tank Watch",
    "Tiffany & Co. Silver Necklace",
    "Diamond Tennis Bracelet (2 Carat)",
    "Patek Philippe Nautilus (Replica)",
    "Vintage Pearl Earrings",
    "Gold Sovereign Coin Ring",
    "Sapphire and Diamond Brooch",
    "Tag Heuer Formula 1 Watch",
    "Bulgari Serpenti Bracelet",
    "Breitling Navitimer",
    "Emerald Cut Ruby Ring",
    "Vintage Chanel Brooch",
    "Platinum Wedding Band",

    # --- Technology & Gaming ---
    "Original 1984 Apple Macintosh Computer",
    "Nintendo Game Boy (Sealed Box)",
    "PlayStation 5 (Gold Plated Edition)",
    "Retro Arcade Cabinet (Pac-Man)",
    "First Generation iPhone (Sealed)",
    "VR Headset (Latest Model)",
    "High-End Gaming PC Setup",
    "Drone with 4K Camera",
    "Vintage Nintendo NES Console",
    "SpaceX Starlink Dish Kit",
    "Tesla Flamethrower",
    "3D Printer (Industrial Grade)",
    "Smart Mirror with Touchscreen",
    "Robot Dog (Boston Dynamics Spot)",
    "Crypto Cold Storage Wallet (Loaded with 0.1 BTC)",
    "Commodore 64 Computer (Boxed)",
    "Atari 2600 Console (Woodgrain)",
    "Sega Genesis Model 1",
    "Sony Walkman TPS-L2 (Original)",
    "Nokia 3310 (Indestructible Brick)",
    "BlackBerry Curve (Vintage)",
    "Palm Pilot PDA",
    "Tamagotchi Original (Gen 1)",
    "Furby (Original 1998)",
    "LaserDisc Player (Pioneer)",
    "Betamax VCR Player",
    "CRT Monitor (Sony Trinitron)",
    "Floppy Disk Box (3.5 inch)",
    "Zip Drive (Iomega)",
    "Dot Matrix Printer",
    "Dial-Up Modem (56k)",
    "Mechanical Keyboard (Model M)",
    "Trackball Mouse (Logitech)",
    "Webcam (Logitech QuickCam)",
    "MP3 Player (Creative Zen)",
    "iPod Classic (1st Gen Scroll Wheel)",
    "Zune HD Media Player",
    "Google Glass (Explorer Edition)",
    "Pebble Smartwatch",
    "Raspberry Pi 4 Model B (8GB)",
    "Arduino Starter Kit",
    "Oculus Rift DK1 Headset",
    "HTC Vive Pro Setup",
    "Valve Index VR Kit",
    "DJI Mavic 3 Cine Drone",
    "GoPro Hero 11 Black",
    "DSLR Camera (Canon 5D Mark IV)",
    "Mirrorless Camera (Sony A7 IV)",
    "Cinema Camera (Red Komodo)",
    "Lens (70-200mm f/2.8)",
    "Gimbal Stabilizer (Ronin)",
    "Studio Microphone (Neumann U87)",
    "Audio Interface (Universal Audio Apollo)",
    "Synthesizer (Korg Minilogue)",
    "Drum Machine (Roland TR-808 Clone)",
    "Turntable (Technics SL-1200)",
    "Headphones (Sennheiser HD 800 S)",
    "Graphics Card (RTX 4090)",
    "Processor (Intel i9-14900K)",
    "Server Rack (42U Enclosure)",
    "Network Switch (Cisco Catalyst)",
    "WiFi 7 Router",
    "Smart Home Hub",
    "Philips Hue Lighting Kit",
    "Nanoleaf Canvas Panels",

    # --- Travel & Experiences ---
    "7-Night Stay in a Water Villa (Maldives)",
    "Private Helicopter Tour of NYC",
    "Safari Trip for Two in Kenya",
    "VIP Tickets to Coachella Music Festival",
    "Zero Gravity Experience Flight",
    "Dinner in the Eiffel Tower",
    "Northern Lights Tour (Iceland)",
    "Disney World All-Access VIP Pass",
    "F1 Grand Prix Paddock Club Tickets",
    "Submarine Dive to the Great Barrier Reef",
    "Castle Stay in Scotland (Weekend)",
    "Hot Air Balloon Ride over Cappadocia",
    "Wine Tasting Tour in Tuscany",
    "Space Camp Experience for Adults",
    "Super Bowl 50 Yard Line Tickets",

    # --- Art & Decor ---
    "Oil Painting: 'Starry Night' (High Quality Replica)",
    "Banksy 'Girl with Balloon' Print",
    "Modern Abstract Metal Sculpture",
    "Hand-Woven Persian Rug",
    "Life-Size Statue of David (Replica)",
    "Japanese Cherry Blossom Watercolor",
    "Vintage Neon Bar Sign",
    "Crystal Chandelier (Swarovski)",
    "Hand-Blown Glass Vase from Murano",
    "Street Art Canvas by Local Artist",
    "Limited Edition KAWS Figure",
    "Salvador Dali Melted Clock Sculpture",
    "Framed Map of the World (17th Century Style)",
    "Bronze Horse Statue",
    "Digital NFT Art Frame",

    # --- Rare Books & Comics ---
    "First Edition 'The Great Gatsby'",
    "Action Comics #1 (Superman Debut - Reprint)",
    "Signed Copy of 'Harry Potter and the Sorcerer's Stone'",
    "The Hobbit (1937 First Edition Replica)",
    "Complete Encyclopedia Britannica Set (1911)",
    "Detective Comics #27 (Batman Debut - Reprint)",
    "Leather Bound Shakespeare Collection",
    "Signed Stephen King Novel",
    "Amazing Fantasy #15 (Spider-Man Debut - Reprint)",
    "Original 1950s Sci-Fi Pulp Magazine",
    "Gutenberg Bible Page (Facsimile)",
    "Da Vinci Code (Signed by Dan Brown)",
    "Vintage Vogue Magazine (1950s)",
    "Sherlock Holmes Collection (Vintage)",
    "Marvel Secret Wars #8 (Black Suit Spidey)",

    # --- Musical Instruments ---
    "Fender Stratocaster Guitar (1960s Reissue)",
    "Violin from 1800s Germany",
    "Steinway Baby Grand Piano",
    "Gibson Les Paul Goldtop",
    "Drum Sticks Signed by Dave Grohl",
    "Vintage Saxophone (Selmer Mark VI)",
    "Harmonica Used by Bob Dylan",
    "Synthesizer (Moog Grandmother)",
    "Ukulele Signed by Israel Kamakawiwo'ole",
    "Electric Bass Guitar (Fender Jazz)",
    "Vintage Accordion",
    "Clarinet (Buffet Crampon)",
    "Microphone Used by Elvis (Replica)",
    "Signed Sheet Music by Beethoven (Facsimile)",
    "Cello (Professional Grade)",

    # --- Vehicles & Models ---
    "1967 Ford Mustang Shelby GT500 (Diecast Model)",
    "Vespa Scooter (Vintage 1970s)",
    "Harley Davidson Leather Jacket",
    "Porsche 911 Engine Block Coffee Table",
    "Model Ship: HMS Victory",
    "Electric Skateboard (Boosted Board)",
    "Vintage Bicycle (Penny Farthing)",
    "Ferrari Key (Collectible)",
    "Lego Millennium Falcon (Ultimate Collector Series)",
    "Remote Control Jet Plane (Gas Powered)",
    "Go-Kart (Professional Racing)",
    "Segway Personal Transporter",
    "Classic Mini Cooper (Toy Car 1960s)",
    "BMW M3 Steering Wheel",
    "Yacht Charter for a Day",
    "1957 Chevy Bel Air (Diecast)",
    "1963 Corvette Sting Ray (Model)",
    "Volkswagen Beetle Type 1 (Model)",
    "Volkswagen T1 Bus (Hippie Van Model)",
    "DeLorean DMC-12 (Diecast)",
    "Ecto-1 Ghostbusters Car (Model)",
    "Batmobile (1989 Burton Version Model)",
    "Batmobile (Tumbler Version Model)",
    "James Bond Lotus Esprit (Submarine Model)",
    "Speed Racer Mach 5 (Diecast)",
    "A-Team Van (Model)",
    "Knight Rider KITT (Model with Light)",
    "Dukes of Hazzard General Lee (Model)",
    "Starsky & Hutch Torino (Model)",
    "Mad Max Interceptor (Weathered Model)",
    "Jurassic Park Jeep Wrangler (Model)",
    "Toyota Supra MK4 (Fast & Furious Model)",
    "Nissan Skyline GT-R R34 (Diecast)",
    "Mazda RX-7 FD (Diecast)",
    "Honda NSX (Original Model)",
    "Ferrari F40 (1:18 Scale)",
    "Lamborghini Countach (1:18 Scale)",
    "McLaren F1 (Diecast)",
    "Bugatti Veyron (Diecast)",
    "Pagani Huayra (Model)",
    "Koenigsegg Agera RS (Model)",
    "Ford GT40 (Le Mans Livery Model)",
    "Porsche 917K (Gulf Livery Model)",
    "Formula 1 Car (Red Bull RB19 Model)",
    "Formula 1 Car (Ferrari F2004 Model)",
    "NASCAR Stock Car (Earnhardt #3 Model)",
    "Monster Truck (Grave Digger Model)",
    "Harley Davidson Fat Boy (Model)",
    "Ducati Panigale V4 (Model)",
    "Kawasaki Ninja H2R (Model)",
    "Vespa 125 (Pastel Blue Model)",
    "Indian Chief Motorcycle (Vintage Model)",
    "Steam Locomotive (Big Boy Model)",
    "Bullet Train (Shinkansen Model)",
    "London Double Decker Bus (Diecast)",
    "Yellow NYC Taxi Cab (Diecast)",
    "Fire Truck (Ladder 49 Model)",
    "Police Interceptor (Crown Vic Model)",
    "Military Tank (M1 Abrams Model)",
    "Fighter Jet (F-22 Raptor Model)",
    "Spitfire Plane (WW2 Model)",
    "B-17 Flying Fortress (Model)",
    "Concorde Supersonic Jet (Model)",
    "Space Shuttle Atlantis (Model)",
    "Saturn V Rocket (Lego Set)",


    # --- Anime & Manga ---
    "Dragon Ball Z: Set of 7 Crystal Dragon Balls",
    "Naruto: Hidden Leaf Village Headband (Replica)",
    "One Piece: Luffy's Straw Hat (Authentic Replica)",
    "Death Note: The Notebook (Replica with Rules)",
    "Attack on Titan: Survey Corps Green Cloak",
    "Sailor Moon: Moon Stick (Proplica Edition)",
    "Fullmetal Alchemist: Edward Elric's Pocket Watch",
    "Pokémon: Master Ball (Diecast Replica)",
    "Demon Slayer: Tanjiro's Nichirin Sword (Replica)",
    "Studio Ghibli: Totoro Plush (Giant Size)",
    "Evangelion: Unit-01 Model Kit (Perfect Grade)",
    "Cowboy Bebop: Spike Spiegel's Jericho 941 (Prop)",
    "JoJo's Bizarre Adventure: Stone Mask Replica",
    "Akira: Kaneda's Red Jacket",
    "Bleach: Ichigo's Hollow Mask",
    "Bleach: Zangetsu Sword Replica",
    "Bleach: Hollow Mask Replica",
    "One Piece: Devil Fruit (Gomu Gomu no Mi) Prop",
    "One Piece: Going Merry Model Ship",
    "One Piece: Zoro's Wado Ichimonji Katana",
    "Naruto: Fourth Hokage's Kunai",
    "Naruto: Akatsuki Cloud Cloak",
    "Dragon Ball: Scouter (Green Lens)",
    "Dragon Ball: Capsule Corp Jacket",
    "Hunter x Hunter: Hunter License Card",
    "Hunter x Hunter: Gon's Fishing Rod Prop",
    "FMA: State Alchemist Silver Watch",
    "FMA: Alphonse Elric Helmet (Wearable)",
    "Death Note: Ryuk Apple Prop",
    "Evangelion: Interface Headset Clips",
    "Evangelion: Lance of Longinus Replica",
    "Gundam: RX-78-2 Gunpla Model (PG Unleashed)",
    "Gundam: Zaku II Commander Type Model",
    "Sailor Moon: Crystal Star Compact",
    "Cardcaptor Sakura: Clow Book & Cards Set",
    "Yu-Gi-Oh!: Millennium Puzzle (Gold Plated)",
    "Yu-Gi-Oh!: Duel Disk Launcher Prop",
    "Pokemon: Pokedex (Kanto Region Replica)",
    "Pokemon: Gym Badge Set (Kanto)",
    "Digimon: Digivice (Original 1999 Version)",
    "Beyblade: Dragoon Beyblade (Original)",
    "YuYu Hakusho: Spirit Detective Badge",
    "Inuyasha: Tessaiga Sword Replica",
    "Cowboy Bebop: Swordfish II Model Ship",
    "Trigun: Vash the Stampede's Revolver Prop",
    "Hellsing: Jackal & Casull Guns Prop",
    "Berserk: Behelit (Egg of the King) Necklace",
    "Berserk: Dragonslayer Greatsword Replica",
    "Attack on Titan: 3D Maneuver Gear Replica",
    "Attack on Titan: Basement Key Necklace",
    "Demon Slayer: Inosuke Boar Mask",
    "Demon Slayer: Nezuko's Bamboo Muzzle",
    "Jujutsu Kaisen: Sukuna's Finger Prop",
    "Jujutsu Kaisen: Prison Realm Cube",
    "Chainsaw Man: Pochita Plush (Life Size)",
    "Spy x Family: Anya Forger Uniform",
    "My Hero Academia: Deku's Iron Soles",
    "My Hero Academia: All Might Action Figure",
    "One Punch Man: Oppai Hoodie",
    "Mob Psycho 100: Dimple Plush",
    "Code Geass: Zero Mask (Wearable)",
    "Gurren Lagann: Core Drill Necklace",
    "Kill la Kill: Scissor Blade (Red)",
    "Akame ga Kill: Murasame Katana",
    "Tokyo Ghoul: Ken Kaneki Mask (Zipper)",
    "Parasyte: Migi Hand Puppet",
    "Steins;Gate: Future Gadget Lab Pin",
    "Steins;Gate: Upa Cushion",
    "Fate/Stay Night: Excalibur Sword Replica",
    "Fate/Zero: Command Spell Temporary Tattoos",
    "Sword Art Online: Elucidator Sword",
    "Sword Art Online: Dark Repulser Sword",
    "No Game No Life: Imanity Chess Piece",
    "Violet Evergarden: Emerald Brooch",
    "Re:Zero: Puck Plushie",
    "Konosuba: Megumin's Staff Replica",
    "Overlord: Ainz Ooal Gown Ring",
    "That Time I Got Reincarnated as a Slime: Rimuru Plush",
    "Shield Hero: Legendary Shield Prop",
    "Goblin Slayer: Helmet Replica",
    "Fire Force: Company 8 Firefighter Jacket",
    "Dr. Stone: Senku's Cola Bottle Prop",
    "Vinland Saga: Thorfinn's Daggers",
    "Black Clover: Five Leaf Clover Grimoire",
    "Fairy Tail: Lucy's Gate Keys Set",
    "Seven Deadly Sins: Lostvayne Sacred Treasure",
    "Soul Eater: Death Scythe Prop",
    "Blue Exorcist: Kurikara Sword",
    "Noragami: Yato's Shrine (Miniature)",
    "Bungo Stray Dogs: Dazai's Bandages",
    "Haikyuu!!: Karasuno High Jersey",
    "Kuroko no Basket: Seirin High Jersey",
    "Blue Lock: Team Z Jersey",
    "Free!: Iwatobi Swim Club Jacket",
    "Yuri on Ice: Makkachin Tissue Box",
    "Fruits Basket: Cat, Dog, Mouse Plush Set",
    "Ouran High School Host Club: Tea Set",
    "Clannad: Big Dango Family Plush",
    "Angel Beats!: SSS Uniform Patch",
    "Your Lie in April: Kaori's Violin Case",
    "Anohana: Menma's Flower Hairpin",
    "Toradora!: Palmtop Tiger Wooden Sword",
    "Maid Sama!: Maid Latte Apron",
    "K-On!: Yui's 'Giita' Guitar Replica",
    "Love Live!: School Idol Festival Light Stick",
    "Gintama: Lake Toya Wooden Sword",
    "JoJo: Stand Arrow Replica",
    "JoJo: Jotaro Kujo Hat",
    "Fist of the North Star: Kenshiro Jacket",
    "Saint Seiya: Sagittarius Gold Cloth Figure",
    "Captain Tsubasa: Nankatsu Jersey",
    "Slam Dunk: Shohoku Jersey #10",
    "Detective Conan: Voice Changing Bowtie",
    "Lupin III: Walther P38 Prop Gun",
    "Astro Boy: Boots Replica",
    "Doraemon: Anywhere Door Model",
    "Spirited Away: No Face Mask",
    "Princess Mononoke: San's Mask & Dagger",
    "Howl's Moving Castle: Calcifer Lamp",
    "Akira: Kaneda's Pill Jacket",

    # --- Video Games (Classics & Modern) ---
    
    # Action & Adventure
    "The Legend of Zelda: Breath of the Wild",
    "God of War (2018)",
    "Grand Theft Auto V",
    "Red Dead Redemption 2",
    "Uncharted 4: A Thief's End",
    "The Last of Us Part II",
    "Horizon Zero Dawn",
    "Assassin's Creed II",
    "Spider-Man (PS4)",
    "Ghost of Tsushima",
    "Batman: Arkham City",
    "Metal Gear Solid V: The Phantom Pain",
    "Shadow of the Colossus",
    "Control",
    "Sekiro: Shadows Die Twice",

    # RPG (Role-Playing Games)
    "The Witcher 3: Wild Hunt",
    "Elden Ring",
    "Skyrim: The Elder Scrolls V",
    "Final Fantasy VII Remake",
    "Mass Effect 2",
    "Persona 5 Royal",
    "Fallout: New Vegas",
    "Dark Souls III",
    "Bloodborne",
    "Cyberpunk 2077",
    "Chrono Trigger",
    "Pokémon Red/Blue (Original Cartridge)",
    "Diablo II: Resurrected",
    "Baldur's Gate 3",
    "Kingdom Hearts II",

    # FPS (First-Person Shooters)
    "Halo: Combat Evolved",
    "Call of Duty 4: Modern Warfare",
    "Doom Eternal",
    "Half-Life 2",
    "BioShock",
    "Overwatch 2",
    "Counter-Strike: Global Offensive",
    "Destiny 2",
    "GoldenEye 007 (N64)",
    "Titanfall 2",
    "Rainbow Six Siege",
    "Team Fortress 2",
    "Wolfenstein II: The New Colossus",
    "Left 4 Dead 2",
    "Apex Legends",

    # Platformers
    "Super Mario Odyssey",
    "Super Mario 64",
    "Celeste",
    "Hollow Knight",
    "Sonic the Hedgehog 2",
    "Donkey Kong Country",
    "Crash Bandicoot N. Sane Trilogy",
    "Spyro Reignited Trilogy",
    "Ori and the Will of the Wisps",
    "Cuphead",
    "LittleBigPlanet",
    "Ratchet & Clank: Rift Apart",
    "Shovel Knight",
    "Banjo-Kazooie",
    "Metroid Dread",

    # Strategy & MOBA
    "League of Legends",
    "Dota 2",
    "Civilization VI",
    "StarCraft II",
    "XCOM 2",
    "Age of Empires II: Definitive Edition",
    "Total War: Warhammer III",
    "Fire Emblem: Three Houses",
    "Crusader Kings III",
    "Command & Conquer: Red Alert 2",

    # Horror & Survival
    "Resident Evil 4 (Remake)",
    "Silent Hill 2",
    "Minecraft",
    "Terraria",
    "Subnautica",
    "Dead Space (Remake)",
    "Alien: Isolation",
    "Amnesia: The Dark Descent",
    "Valheim",
    "The Forest",

    # Fighting
    "Street Fighter 6",
    "Super Smash Bros. Ultimate",
    "Tekken 7",
    "Mortal Kombat 11",
    "Dragon Ball FighterZ",
    "Soulcalibur VI",
    "Marvel vs. Capcom 2",
    "Guilty Gear Strive",
    "Injustice 2",
    "King of Fighters XV",

    # Indie Hits & Simulation
    "Stardew Valley",
    "Undertale",
    "Animal Crossing: New Horizons",
    "The Sims 4",
    "Among Us",
    "Hades",
    "Disco Elysium",
    "Rocket League",
    "Portal 2",
    "Tetris Effect",
    "Metroid Prime (GameCube)",
    "Castlevania: Symphony of the Night",
    "Silent Hill 2",
    "Metal Gear Solid 3: Snake Eater",
    "Resident Evil 2 (Original)",
    "Final Fantasy VI",
    "Chrono Cross",
    "EarthBound",
    "Street Fighter II Turbo",
    "Mega Man X",
    "Deus Ex (Original)",
    "System Shock 2",
    "Thief: The Dark Project",
    "Baldur's Gate II: Shadows of Amn",
    "Planescape: Torment",
    "Fallout 2",
    "Grim Fandango",
    "The Secret of Monkey Island",
    "Day of the Tentacle",
    "Myst",
    "The Sims (Original)",
    "RollerCoaster Tycoon 2",
    "Age of Empires",
    "Warcraft III: Reign of Chaos",
    "Diablo",
    "Quake III Arena",
    "Unreal Tournament 2004",
    "Return to Castle Wolfenstein",
    "Far Cry 3",
    "Crysis (Maximum Edition)",
    "BioShock Infinite",
    "Mass Effect (Original)",
    "Dragon Age: Origins",
    "Star Wars: Knights of the Old Republic",
    "Star Wars: Battlefront II (2005)",
    "Need for Speed: Underground 2",
    "Burnout 3: Takedown",
    "Gran Turismo 3: A-Spec",
    "Forza Horizon 5",
    "Mario Kart 8 Deluxe",
    "Super Smash Bros. Melee",
    "Luigi's Mansion",
    "Pikmin 2",
    "Animal Crossing (GameCube)",
    "Fire Emblem: Path of Radiance",
    "Xenoblade Chronicles",
    "Persona 4 Golden",
    "Yakuza 0",
    "Nier: Automata",
    "Bayonetta",
    "Devil May Cry 3: Dante's Awakening",
    "Resident Evil Village",
    "Resident Evil 7: Biohazard",
    "Dead Rising",
    "Lost Planet: Extreme Condition",
    "Gears of War",
    "Halo 3",
    "Halo: Reach",
    "Fable II",
    "Viva Piñata",
    "Sea of Thieves",
    "Grounded",
    "Outer Wilds",
    "Tunic",
    "Slay the Spire",
    "Dead Cells",
    "Inscryption",
    "Return of the Obra Dinn",
    "Papers, Please",
    "Hotline Miami",
    "Katana ZERO",
    "Spelunky 2",
    "The Binding of Isaac: Rebirth",
    "Risk of Rain 2",
    "Deep Rock Galactic",
    "Factorio",
    "Satisfactory",
    "RimWorld",
    "Dwarf Fortress",
    "Kerbal Space Program",
    "Cities: Skylines",
    "Planet Zoo",
    "Jurassic World Evolution 2",
    "No Man's Sky",
    "Elite Dangerous",
    "Star Citizen (Ship Package)",
    "EVE Online (PLEX Pack)",
    "World of Warcraft (Collector's Edition)",
    "Final Fantasy XIV (Collector's Edition)",
    "Guild Wars 2",
    "Black Desert Online",
    "Lost Ark",
    "Genshin Impact (Primogem Pack)",
    "Honkai: Star Rail",
    "Valorant (Skin Bundle)",
    "Fortnite (V-Bucks Card)",
    "Roblox (Gift Card)",
    "PUBG: Battlegrounds",
    "Escape from Tarkov (Edge of Darkness)",
    "Rust",
# Movie Memorabilia & Collectibles
    "The Shawshank Redemption (Limited Edition Blu-ray)",
    "The Godfather (Original 1972 Poster)",
    "The Dark Knight (Batpod Model)",
    "Pulp Fiction (Signed Script)",
    "Schindler's List ( commemorative Box Set)",
    "12 Angry Men (Criterion Collection)",
    "Inception (Spinning Top Prop)",
    "Fight Club (Soap Bar Prop)",
    "Forrest Gump (Bubba Gump Hat)",
    "The Matrix (Red/Blue Pill Prop)",
    "Goodfellas (Signed Cast Photo)",
    "The Empire Strikes Back (Original VHS)",
    "One Flew Over the Cuckoo's Nest (Novel)",
    "Interstellar (TARS Model)",
    "Parasite (Scholar's Rock Prop)",
    "Spirited Away (No Face Plush)",
    "City of God (Brazilian Release Poster)",
    "Se7en (Box Prop)",
    "The Silence of the Lambs (Hannibal Mask Replica)",
    "It's a Wonderful Life (Vintage Bell)",
    "Seven Samurai (Criterion DVD)",
    "Life Is Beautiful (Soundtrack Vinyl)",
    "The Usual Suspects (Keyser Söze Sketch)",
    "Leon: The Professional (Potted Plant Prop)",
    "Saving Private Ryan (Normandy Sand Vial)",
    "American History X (Film Reel)",
    "Back to the Future (Hoverboard Replica)",
    "Terminator 2: Judgment Day (Endoarm Replica)",
    "Modern Times (Charlie Chaplin Hat)",
    "Psycho (Bates Motel Key)",
    "The Green Mile (Mouse Prop)",
    "The Intouchables (Original French Poster)",
    "Whiplash (Drumstick Signed by J.K. Simmons)",
    "Gladiator (Maximus Helmet Replica)",
    "The Prestige (Magic Bird Cage Prop)",
    "The Departed (Signed Script by Scorsese)",
    "The Pianist (Sheet Music Replica)",
    "Memento (Polaroid Prop Set)",
    "Apocalypse Now (Ride of the Valkyries Vinyl)",
    "Raiders of the Lost Ark (Golden Idol Replica)",
    "Django Unchained (Bounty Hunter Wanted Poster)",
    "WALL-E (Diecast Model)",
    "The Lives of Others (Stasi Listening Device Prop)",
    "Sunset Blvd. (Vintage Script)",
    "Paths of Glory (Criterion Blu-ray)",
    "The Shining (Overlook Hotel Carpet Swatch)",
    "The Great Dictator (Speech Manuscript Replica)",
    "Avengers: Infinity War (Infinity Gauntlet Replica)",
    "Aliens (Pulse Rifle Replica)",
    "American Beauty (Rose Petal Prop)",
    "Spider-Man: Into the Spider-Verse (Poster)",
    "Coco (Guitar Replica)",
    "The Dark Knight Rises (Bane Mask)",
    "Joker (Clown Mask Replica)",
    "Braveheart (Freedom Sword Replica)",
    "Toy Story (Woody & Buzz Figures)",
    "Amadeus (Soundtrack CD)",
    "Inglourious Basterds (Baseball Bat Prop)",
    "Good Will Hunting (Math Problem Prop)",
    "Star Wars: A New Hope (1977 Poster)",
    "2001: A Space Odyssey (HAL 9000 Eye Replica)",
    "Reservoir Dogs (Ear Prop)",
    "Requiem for a Dream (Soundtrack Vinyl)",
    "Vertigo (Hitchcock Signed Photo)",
    "Eternal Sunshine of the Spotless Mind (Orange Hoodie)",
    "Citizen Kane (Rosebud Sled Replica)",
    "Full Metal Jacket (Peace Button)",
    "A Clockwork Orange (Bowler Hat)",
    "Taxi Driver (Mohawk Wig)",
    "Scarface (The World Is Yours Statue)",
    "Lawrence of Arabia (70mm Film Cell)",
    "Double Indemnity (Vintage Poster)",
    "Amélie (Garden Gnome Prop)",
    "To Kill a Mockingbird (First Edition Book)",
    "A Separation (Signed DVD)",
    "Metropolis (1927 Poster Reprint)",
    "L.A. Confidential (Badge Replica)",
    "Die Hard (Nakatomi Plaza Model)",
    "Snatch (Diamond Prop)",
    "Yojimbo (Katana Replica)",
    "Batman Begins (Batarang Prop)",
    "Up (Grape Soda Pin)",
    "Heat (Bank Heist Mask)",
    "Indiana Jones and the Last Crusade (Grail Diary)",
    "Monty Python and the Holy Grail (Coconut Props)",
    "Rashomon (Criterion Collection)",
    "Once Upon a Time in the West (Harmonica Prop)",
    "Jaws (Shark Tooth Necklace)",
    "Chinatown (Fedora Hat)",
    "Room (Drawing Prop)",
    "The Grand Budapest Hotel (Mendl's Box)",
    "Blade Runner (Origami Unicorn)",
    "No Country for Old Men (Coin Prop)",
    "V for Vendetta (Guy Fawkes Mask)",
    "Inside Out (Joy Figure)",
    "The Thing (Alien Lifeform Prop)",
    "Trainspotting (Poster)",
    "The Bridge on the River Kwai (Whistle Prop)",
    "Fargo (Wood Chipper Model)"

    # --- Classics & Golden Age ---
    "Casablanca (Letters of Transit Prop)",
    "Gone with the Wind (Scarlett's Curtain Dress Fabric)",
    "The Wizard of Oz (Ruby Slippers Replica)",
    "Singin' in the Rain (Gene Kelly's Umbrella)",
    "Roman Holiday (Vespa Scooter Model)",
    "Rebel Without a Cause (Jim Stark's Red Jacket)",
    "Some Like It Hot (Vintage Maracas)",
    "Breakfast at Tiffany's (Cigarette Holder Prop)",
    "The Birds (Prop Crow)",
    "Dr. Strangelove (Survival Kit Contents)",
    "The Sound of Music (Acoustic Guitar Replica)",
    "The Graduate (Alfa Romeo Spider Model)",
    "Planet of the Apes (Statue of Liberty Fragment Prop)",
    "Butch Cassidy and the Sundance Kid (Bowler Hat)",
    "Midnight Cowboy (Buckskin Jacket)",
    "A Streetcar Named Desire (Vintage T-Shirt)",
    "On the Waterfront (Docker's Hook Prop)",
    "Ben-Hur (Chariot Wheel Fragment)",
    "The Ten Commandments (Stone Tablet Prop)",
    "Cleopatra (Golden Headdress Replica)",
    "Mary Poppins (Parrot Head Umbrella)",
    "Bullitt (Ford Mustang GT 390 Model)",
    "Easy Rider (Captain America Helmet)",
    "Dirty Harry (Inspector Badge)",
    "The French Connection (Pork Pie Hat)",
    "Deliverance (Banjo Prop)",
    "The Exorcist (Regan's Bed Post)",
    "American Graffiti (Mel's Diner Menu)",
    "The Sting (Deck of Cards)",
    "Annie Hall (Vest and Tie Set)",
    "Close Encounters of the Third Kind (Mashed Potato Sculpture)",
    "Grease (T-Birds Leather Jacket)",
    "Superman: The Movie (Green Crystal Prop)",
    "The Deer Hunter (Bandana)",
    "Airplane! (Otto the Autopilot Pilot Manual)",
    "The Blues Brothers (Ray-Ban Wayfarers)",
    "Poltergeist (Clown Doll Replica)",
    "Risky Business (Wayfarer Sunglasses)",
    "The Breakfast Club (Detention Slip Prop)",
    "Ferris Bueller's Day Off (Ferrari 250 GT California Model)",
    "Stand By Me (Gordie's Cap)",
    "Platoon (Helmet with Graffiti)",
    "The Princess Bride (Inigo Montoya's Sword Replica)",
    "Dirty Dancing 'Kellerman's' Staff Shirt",
    "Lethal Weapon (LAPD Badge)",
    "Who Framed Roger Rabbit (Barrel of 'Dip')",
    "Rain Man (Casino Chips)",
    "Dead Poets Society (Book of Verse)",
    "Do the Right Thing (Boombox Prop)",
    "When Harry Met Sally (Katz's Deli Menu)",
    "Edward Scissorhands (Scissor Glove Replica)",
    "Home Alone (Battle Plan Drawn Map)",
    "Thelma & Louise (Thunderbird Convertible Model)",
    "Unforgiven (Sheriff Badge)",
    "A Few Good Men (Judge's Gavel)",
    "Groundhog Day (Alarm Clock Prop)",
    "The Nightmare Before Christmas (Jack Skellington Head)",
    "Mrs. Doubtfire (Latex Mask Prop)",
    "The Lion King (Simba Plush - Vintage)",
    "Speed (Bus 2525 Diecast Model)",
    "Dumb and Dumber (Orange Tuxedo)",
    "Apollo 13 (Flight Manual Replica)",
    "Clueless (Yellow Plaid Skirt)",
    "Independence Day (Alien Head Prop)",
    "Jerry Maguire (Mission Statement Manuscript)",
    "Titanic (Heart of the Ocean Necklace Replica)",
    "Men in Black (Neuralyzer Prop)",
    "The Fifth Element (Multipass Prop)",
    "The Big Lebowski (The Dude's Bowling Shirt)",
    "The Truman Show ('How's It Going to End?' Button)",
    "Rushmore (Yankee Promethium Pin)",
    "Shakespeare in Love (Quill Pen)",
    "The Sixth Sense (Tape Recorder Prop)",
    "Office Space (Red Swingline Stapler)",
    "The Blair Witch Project (Stick Figure Totem)",
    "Cast Away (Wilson Volleyball Replica)",
    "Almost Famous (Stillwater Backstage Pass)",
    "Crouching Tiger, Hidden Dragon (Green Destiny Sword)",
    "Shrek ('Beware of Ogre' Sign)",
    "Ocean's Eleven (Bellagio Poker Chip)",
    "The Royal Tenenbaums (Adidas Tracksuit)",
    "Mulholland Drive (Blue Key Prop)",
    "Minority Report (Pre-Cog Wooden Ball)",
    "Gangs of New York (Bill the Butcher's Top Hat)",
    "Lost in Translation (Pink Wig)",
    "Kill Bill: Vol. 1 ('Pussy Wagon' Key Chain)",
    "School of Rock (Guitar Pick of Destiny)",
    "Elf (Buddy's Hat)",
    "Shaun of the Dead (Cricket Bat Prop)",
    "Anchorman (Channel 4 News Team Ring)",
    "Napoleon Dynamite ('Vote for Pedro' T-Shirt)",
    "Mean Girls (Burn Book Replica)",
    "The Notebook (Bundle of Letters Prop)",
    "Brokeback Mountain (Shirts on Hanger Prop)",
    "The Devil Wears Prada (Runway Magazine)",
    "Borat (Grey Suit Replica)",
    "Little Miss Sunshine (VW Bus Diecast)",
    "Pan's Labyrinth (Piece of Chalk Prop)",
    "There Will Be Blood (Bowling Pin Prop)",
    "Superbad (McLovin Fake ID)",
    "Juno (Hamburger Phone)",
    "Slumdog Millionaire (20 Million Rupee Note Prop)",
    "Avatar (Na'vi Dagger Replica)",
    "District 9 (Alien Weapon Prop)",
    "The Hangover (Baby Carrier)",
    "The Social Network (Facebook Business Card)",
    "Black Swan (Ballerina Music Box)",
    "The King's Speech (Vintage Microphone)",
    "Drive (Scorpion Jacket Replica)",
    "The Girl with the Dragon Tattoo (Laptop Prop)",
    "Les Misérables (French Flag Prop)",
    "The Wolf of Wall Street (Quaalude Bottle Prop)",
    "Her (Safety Pin Prop)",
    "Guardians of the Galaxy (Awesome Mix Vol. 1 Cassette)",
    "Ex Machina (Ava's Drawing)",
    "Mad Max: Fury Road (War Boy Steering Wheel)",
    "La La Land (Yellow Dress Replica)",
    "Moonlight (Grillz Prop)",
    "Get Out (Teacup and Spoon)",
    "The Shape of Water (Egg Timer)",
    "Black Panther (Wakandan Necklace)",
    "Hereditary (Sketchbook Prop)",
    "Once Upon a Time... in Hollywood (Rick Dalton Poster)",
    "1917 (Soldier's Ring)",
    "Everything Everywhere All At Once (Googly Eye Prop)",
    "Barbie (Neon Rollerblades)",
    "Oppenheimer (Fedora Hat Replica)"
]